name: Terraform

on:
  push:
    branches:
      - ec2

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up terraform
      uses: hashicorp/setup-terraform@v2
      with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Setup Terraform Backend
      id: backend
      run: |
        cat > backend.tf << EOF
        terraform {
            cloud {
                organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
                workspaces {
                name = "${{ secrets.TF_EC2_WORKSPACE }}"
                }
            }
        }
        EOF

    - name: Initialize TErraform
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan
    
    - name: Deploy Infrastructure
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: github.event_name == 'push' && contains(github.event.head_commit.message, 'destroy')
      working-directory: infra
      run: terraform destroy -auto-approve
