name: Terraform

on:
  push:
    branches:
      - ec2

jobs:
  infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up terraform
      uses: hashicorp/setup-terraform@v2
      with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Setup Terraform Backend
      id: backend
      run: |
        cat > backend.tf << EOF
        terraform {
            cloud {
                organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
                workspaces {
                name = "${{ secrets.TF_EC2_WORKSPACE }}"
                }
            }
        }
        EOF

    - name: Initialize Terraform
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      if: github.event_name == 'push' && contains(github.event.head_commit.message, 'deploy')
      run: terraform validate -no-color

    - name: Terraform Plan
      if: github.event_name == 'push' && contains(github.event.head_commit.message, 'deploy')
      run: terraform plan
    
    - name: Deploy Infrastructure
      if: github.event_name == 'push' && contains(github.event.head_commit.message, 'deploy')
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: github.event_name == 'push' && contains(github.event.head_commit.message, 'destroy')
      run: terraform destroy -auto-approve
  
  ssh_into_ec2:
      runs-on: ubuntu-latest
      needs: infra
      steps:
        - name: Get Public IP
          id: get_public_ip
          run: echo "::set-output name=public_ip::$(terraform output public_ip)"
          working-directory: infra
  
        - name: SSH into EC2 Instance
          if: github.event_name == 'push' && contains(github.event.head_commit.message, 'ssh')
          run: |
            PRIVATE_KEY="${{ secrets.PRIVATE_KEY_SECRET }}"
            PUBLIC_IP=${{ needs.infra.outputs.get_public_ip }}
            echo "$PRIVATE_KEY" > private_key.pem
            chmod 600 private_key.pem
            ssh -i private_key.pem ec2-user@$PUBLIC_IP "echo Hello from SSH"
          env:
            PRIVATE_KEY_SECRET: ${{ secrets.PRIVATE_KEY_SECRET }}